start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
ping -n 60 localhost
start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
ping -n 60 localhost
start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
ping -n 60 localhost
start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
ping -n 60 localhost
start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
ping -n 60 localhost
start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
ping -n 60 localhost
start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
ping -n 60 localhost
start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
ping -n 60 localhost
start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
ping -n 60 localhost
start python "C:\Users\nikhi\PycharmProjects\learnPython\greedy_with_subjects.py"
